name: Deploy to shinyapps.io

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl libcurl4-openssl-dev

      - name: Install R package dependencies
        run: |
          install.packages(
            c("rsconnect", "shiny", "tidyverse", "ggforce", "hexbin"),
            repos = "https://cloud.r-project.org"
          )
        shell: Rscript {0}

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_SERVER: ${{ secrets.SHINYAPPS_SERVER }}
        run: |
          library(rsconnect)
          rsconnect::setAccountInfo(
            name = Sys.getenv("SHINYAPPS_ACCOUNT"),
            token = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )
          rsconnect::deployApp(
            appDir = "ShotLocationsApp",
            account = Sys.getenv("SHINYAPPS_ACCOUNT"),
            server = Sys.getenv("SHINYAPPS_SERVER")
          )
        shell: Rscript {0}
